version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g hexo-cli
      - npm install

  build:
    commands:
      - hexo generate
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
