version: 0.2

# CodeBuild でのビルドの各段階で実行するコマンドを定義する
phases:
  # ビルド前に必要なパッケージのインストールを実行
  pre_build:
    commands:
      - npm install
      - npm install -g hexo
  # 静的サイトとしてのビルドを実行
  build:
    commands:
      - hexo generate
# デプロイする際に public フォルダ以下の内容を指定した S3 バ ケットにアップロードするように設定
artifacts:
  files:
    - ’**/*’
  base-directory: ’public’
